function Write_Test_Looking_Data(fid, htmlFid, preTestIndex,  badTrial, ...
        SN, trial, preTestEvent, timeOn, timeOn2, latency, timeOff, ...
        timeOff2, lookAway1, lookAway2, AGR, SIM, KAPPA, fixedHabituation)
    tsvFormat = Get_File_Columns('tsv', 'test', 0, badTrial, fixedHabituation);
    htmlFormat = Get_File_Columns('html', 'test',  0, badTrial, fixedHabituation);
    columnBg = '#FFFFFF';
    if (mod(preTestIndex, 2))
        columnBg = '#DDDDDD';
    end
    if (fixedHabituation)
        fprintf(fid, tsvFormat, SN, SN, ...
                    trial, preTestEvent, timeOn, timeOn2, latency, timeOff, ...
                    timeOff2, lookAway1, lookAway2, AGR, SIM, KAPPA);
        fprintf(htmlFid, htmlFormat, ...
                        columnBg, trial, preTestEvent, ...
                        timeOn, timeOn2, latency, ...
                        timeOff, lookAway1, ...
                        AGR, SIM, ...
                        KAPPA);
    else
        fprintf(fid, tsvFormat, ...
                    SN, trial, preTestEvent, timeOn, timeOn2, latency, timeOff, ...
                    timeOff2, lookAway1, lookAway2, AGR, SIM, KAPPA);
        fprintf(htmlFid, htmlFormat, ...
                        columnBg, trial, preTestEvent, ...
                        timeOn, timeOn2, latency, ...
                        timeOff, lookAway1, ...
                        AGR, SIM, ...
                        KAPPA);
    end
    clear tsvFormat htmlFormat columnBg;